// backend-ts/templates/vue/src/components/blocks/RatingStars.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useAppStore } from '../../composables/useAppStore';
import { Icon } from '@iconify/vue';

const props = withDefaults(defineProps<{
  initialRating?: number;
  maxStars?: number;
  readOnly?: boolean;
}>(), { initialRating: 0, maxStars: 5, readOnly: false });

const emit = defineEmits<{ rate: [rating: number] }>();
const { toastMessage, toastVisible } = useAppStore();
const rating = ref(props.initialRating);
const hover = ref(0);

const handleRate = (star: number) => {
  if (props.readOnly) return;
  rating.value = star;
  emit('rate', star);
  toastMessage.value = `Rated ${star} star${star !== 1 ? 's' : ''}`;
  toastVisible.value = true;
  setTimeout(() => { toastVisible.value = false; }, 2500);
};
</script>

<template>
  <div class="inline-flex items-center gap-0.5">
    <button v-for="star in maxStars" :key="star" @click="handleRate(star)" @mouseenter="!readOnly && (hover = star)" @mouseleave="!readOnly && (hover = 0)" class="transition-transform duration-150" :class="readOnly ? 'cursor-default' : 'cursor-pointer hover:scale-125 active:scale-95'" :disabled="readOnly" :aria-label="`Rate ${star} star${star !== 1 ? 's' : ''}`">
      <Icon :icon="(hover || rating) >= star ? 'mdi:star' : 'mdi:star-outline'" :width="20" :class="(hover || rating) >= star ? 'text-yellow-400' : 'text-gray-300'" class="transition-colors duration-150" />
    </button>
  </div>
</template>

// backend-ts/templates/react/src/components/blocks/RatingStars.tsx
import { FiStar } from 'react-icons/fi';
import toast from 'react-hot-toast';
import { cn } from '@/lib/utils';
import { useState } from 'react';

interface RatingStarsProps {
  initialRating?: number;
  maxStars?: number;
  onRate?: (rating: number) => void;
  readOnly?: boolean;
  size?: 'sm' | 'md' | 'lg';
  className?: string;
}

export function RatingStars({ initialRating = 0, maxStars = 5, onRate, readOnly = false, size = 'md', className }: RatingStarsProps) {
  const [rating, setRating] = useState(initialRating);
  const [hover, setHover] = useState(0);
  const iconSize = size === 'sm' ? 'w-4 h-4' : size === 'lg' ? 'w-7 h-7' : 'w-5 h-5';

  const handleRate = (star: number) => {
    if (readOnly) return;
    setRating(star);
    onRate?.(star);
    toast.success(`Rated ${star} star${star !== 1 ? 's' : ''}`);
  };

  return (
    <div className={cn('inline-flex items-center gap-0.5', className)}>
      {Array.from({ length: maxStars }, (_, i) => i + 1).map(star => (
        <button key={star} onClick={() => handleRate(star)} onMouseEnter={() => !readOnly && setHover(star)} onMouseLeave={() => !readOnly && setHover(0)} className={cn('transition-transform duration-150', readOnly ? 'cursor-default' : 'cursor-pointer hover:scale-125 active:scale-95')} disabled={readOnly} aria-label={`Rate ${star} star${star !== 1 ? 's' : ''}`}>
          <FiStar className={cn(iconSize, 'transition-colors duration-150', (hover || rating) >= star ? 'fill-yellow-400 text-yellow-400' : 'text-gray-300')} />
        </button>
      ))}
    </div>
  );
}
