// backend-ts/templates/astro/src/components/blocks/FilterChips.tsx
import { useState } from 'react';

interface FilterChip { id: string; label: string; }

interface FilterChipsProps {
  chips: FilterChip[];
  initialSelected?: string[];
  onChange?: (selected: string[]) => void;
  multiple?: boolean;
}

export function FilterChips({ chips, initialSelected = [], onChange, multiple = true }: FilterChipsProps) {
  const [selected, setSelected] = useState<string[]>(initialSelected);

  const handleToggle = (chipId: string) => {
    const next = multiple
      ? (selected.includes(chipId) ? selected.filter(id => id !== chipId) : [...selected, chipId])
      : (selected.includes(chipId) ? [] : [chipId]);
    setSelected(next);
    onChange?.(next);
  };

  return (
    <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
      {chips.map(chip => (
        <button key={chip.id} onClick={() => handleToggle(chip.id)} style={{ padding: '6px 14px', borderRadius: '9999px', fontSize: '14px', fontWeight: 500, border: 'none', cursor: 'pointer', transition: 'all 0.2s', background: selected.includes(chip.id) ? '#8b5cf6' : '#f3f4f6', color: selected.includes(chip.id) ? '#fff' : '#4b5563' }}>
          {chip.label}
        </button>
      ))}
    </div>
  );
}

// backend-ts/templates/vue/src/components/blocks/FilterChips.vue
<script setup lang="ts">
interface FilterChip { id: string; label: string; }

const props = withDefaults(defineProps<{
  chips: FilterChip[];
  modelValue: string[];
  multiple?: boolean;
}>(), { multiple: true });

const emit = defineEmits<{ 'update:modelValue': [selected: string[]] }>();

const handleToggle = (chipId: string) => {
  if (props.multiple) {
    emit('update:modelValue', props.modelValue.includes(chipId) ? props.modelValue.filter(id => id !== chipId) : [...props.modelValue, chipId]);
  } else {
    emit('update:modelValue', props.modelValue.includes(chipId) ? [] : [chipId]);
  }
};
</script>

<template>
  <div class="flex flex-wrap gap-2">
    <button v-for="chip in chips" :key="chip.id" @click="handleToggle(chip.id)" class="px-3 py-1.5 rounded-full text-sm font-medium transition-all duration-200 active:scale-95" :class="modelValue.includes(chip.id) ? 'bg-primary text-primary-foreground shadow-sm' : 'bg-gray-100 text-gray-600 hover:bg-gray-200'">
      {{ chip.label }}
    </button>
  </div>
</template>
