// backend-ts/templates/astro/src/components/blocks/SearchBar.tsx
import { useState, useRef, useEffect, useCallback } from 'react';

interface SearchBarProps {
  onSearch: (query: string) => void;
  placeholder?: string;
  debounceMs?: number;
}

export function SearchBar({ onSearch, placeholder = 'Search...', debounceMs = 300 }: SearchBarProps) {
  const [query, setQuery] = useState('');
  const timerRef = useRef<ReturnType<typeof setTimeout>>();

  const handleChange = useCallback((value: string) => {
    setQuery(value);
    clearTimeout(timerRef.current);
    timerRef.current = setTimeout(() => onSearch(value), debounceMs);
  }, [onSearch, debounceMs]);

  const handleClear = () => { setQuery(''); onSearch(''); };
  useEffect(() => () => clearTimeout(timerRef.current), []);

  return (
    <div style={{ position: 'relative' }}>
      <input type="text" value={query} onChange={e => handleChange(e.target.value)} placeholder={placeholder} style={{ width: '100%', padding: '10px 40px 10px 12px', border: '1px solid #e5e7eb', borderRadius: '8px', fontSize: '14px', outline: 'none' }} />
      {query && <button onClick={handleClear} style={{ position: 'absolute', right: '8px', top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', cursor: 'pointer', fontSize: '16px', color: '#9ca3af' }} aria-label="Clear">{'\u2715'}</button>}
    </div>
  );
}

// backend-ts/templates/vue/src/components/blocks/SearchBar.vue
<script setup lang="ts">
import { ref, onUnmounted } from 'vue';
import { Icon } from '@iconify/vue';

const props = withDefaults(defineProps<{
  placeholder?: string;
  debounceMs?: number;
}>(), { placeholder: 'Search...', debounceMs: 300 });

const emit = defineEmits<{ search: [query: string] }>();
const query = ref('');
let timer: ReturnType<typeof setTimeout>;

const handleInput = (value: string) => {
  query.value = value;
  clearTimeout(timer);
  timer = setTimeout(() => emit('search', value), props.debounceMs);
};

const handleClear = () => { query.value = ''; emit('search', ''); };

onUnmounted(() => clearTimeout(timer));
</script>

<template>
  <div class="relative">
    <Icon icon="mdi:magnify" :width="16" class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
    <input type="text" :value="query" @input="handleInput(($event.target as HTMLInputElement).value)" :placeholder="placeholder" class="w-full pl-10 pr-10 py-2.5 rounded-lg border border-gray-200 bg-white text-sm focus:outline-none focus:ring-2 focus:ring-primary/20 focus:border-primary transition-colors" />
    <button v-if="query" @click="handleClear" class="absolute right-3 top-1/2 -translate-y-1/2 p-0.5 rounded-full hover:bg-gray-100 transition-colors" aria-label="Clear search">
      <Icon icon="mdi:close" :width="16" class="text-gray-400" />
    </button>
  </div>
</template>
