// backend-ts/templates/astro/src/components/ui/SafeButton.tsx
import * as React from "react";

/**
 * SafeButton for Astro React islands — warns when onClick is missing.
 */
export const SafeButton = ({
  onClick,
  children,
  type,
  disabled,
  className,
  ...props
}: React.ButtonHTMLAttributes<HTMLButtonElement>) => {
  if (import.meta.env.DEV && !onClick && type !== 'submit' && !disabled) {
    const label = typeof children === 'string' ? children : 'unknown';
    console.error(`[Drape] Dead button detected: "${label}" has no onClick handler.`);
  }
  return (
    <button onClick={onClick} type={type || 'button'} disabled={disabled} className={className} {...props}>
      {children}
    </button>
  );
};

// backend-ts/templates/vue/src/components/SafeButton.vue
<script setup lang="ts">
/**
 * SafeButton — warns in dev mode when no click handler is provided.
 */
import { useAttrs, onMounted, getCurrentInstance } from 'vue';

const props = defineProps<{
  type?: 'button' | 'submit' | 'reset';
  disabled?: boolean;
}>();

const attrs = useAttrs();

onMounted(() => {
  if (import.meta.env.DEV && !attrs.onClick && props.type !== 'submit' && !props.disabled) {
    const instance = getCurrentInstance();
    const label = instance?.vnode?.el?.textContent?.trim() || 'unknown';
    console.error(`[Drape] Dead button detected: "${label}" has no @click handler. Add a real handler or remove the button.`);
  }
});
</script>

<template>
  <button
    :type="type || 'button'"
    :disabled="disabled"
    v-bind="$attrs"
    class="inline-flex items-center justify-center rounded-md text-sm font-medium transition-colors focus-visible:outline-none disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2"
  >
    <slot />
  </button>
</template>
