// backend-ts/templates/nextjs/app/components/ui/avatar.tsx
import * as React from "react";
import { cn } from "@/app/lib/utils";

interface AvatarProps extends React.HTMLAttributes<HTMLDivElement> {
  src?: string;
  alt?: string;
  fallback?: string;
  size?: "sm" | "md" | "lg";
}

const sizes = { sm: "h-8 w-8", md: "h-10 w-10", lg: "h-14 w-14" };

function Avatar({ src, alt, fallback, size = "md", className, ...props }: AvatarProps) {
  return (
    <div className={cn("relative flex shrink-0 overflow-hidden rounded-full", sizes[size], className)} {...props}>
      {src ? (
        <img className="aspect-square h-full w-full object-cover" src={src} alt={alt || ""} />
      ) : (
        <div className="flex h-full w-full items-center justify-center rounded-full bg-muted text-sm font-medium">
          {fallback || alt?.charAt(0)?.toUpperCase() || "?"}
        </div>
      )}
    </div>
  );
}

export { Avatar };

// backend-ts/templates/vue/src/components/ui/Avatar.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { cn } from '../../lib/utils'

const props = withDefaults(defineProps<{
  src?: string
  alt?: string
  fallback?: string
  size?: 'sm' | 'md' | 'lg'
}>(), {
  alt: '',
  fallback: '?',
  size: 'md',
})

const imgError = ref(false)

const sizeClasses: Record<string, string> = {
  sm: 'h-8 w-8 text-xs',
  md: 'h-10 w-10 text-sm',
  lg: 'h-14 w-14 text-lg',
}

const classes = computed(() =>
  cn(
    'relative inline-flex shrink-0 items-center justify-center overflow-hidden rounded-full bg-surface-light',
    sizeClasses[props.size],
  )
)

const showImage = computed(() => props.src && !imgError.value)
</script>

<template>
  <span :class="classes">
    <img
      v-if="showImage"
      :src="src"
      :alt="alt"
      class="aspect-square h-full w-full object-cover"
      @error="imgError = true"
    />
    <span v-else class="font-medium text-text-secondary">
      {{ fallback }}
    </span>
  </span>
</template>
