// backend-ts/templates/vue/src/components/blocks/LikeButton.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useAppStore } from '../../composables/useAppStore';
import { Icon } from '@iconify/vue';

const props = withDefaults(defineProps<{
  itemId: string;
  initialLiked?: boolean;
  showCount?: boolean;
  initialCount?: number;
}>(), { initialLiked: false, showCount: false, initialCount: 0 });

const emit = defineEmits<{ toggle: [liked: boolean] }>();
const { toggleFavorite } = useAppStore();
const liked = ref(props.initialLiked);
const count = ref(props.initialCount);

const handleToggle = () => {
  liked.value = !liked.value;
  count.value += liked.value ? 1 : -1;
  if (count.value < 0) count.value = 0;
  toggleFavorite(props.itemId);
  emit('toggle', liked.value);
};
</script>

<template>
  <button @click="handleToggle" class="rounded-full transition-all duration-200 hover:scale-110 active:scale-95 p-2" :aria-label="liked ? 'Remove from favorites' : 'Add to favorites'">
    <Icon :icon="liked ? 'mdi:heart' : 'mdi:heart-outline'" :width="20" :class="liked ? 'text-red-500' : 'text-gray-400 hover:text-red-400'" class="transition-colors duration-200" />
    <span v-if="showCount" class="text-xs text-gray-500 ml-1">{{ count }}</span>
  </button>
</template>

// backend-ts/templates/nextjs/app/components/blocks/LikeButton.tsx
"use client";
import { useState } from 'react';
import { FiHeart } from 'react-icons/fi';
import { toast } from 'sonner';
import { cn } from '@/lib/utils';

interface LikeButtonProps {
  itemId: string;
  initialLiked?: boolean;
  onToggle?: (liked: boolean) => void;
  size?: 'sm' | 'md' | 'lg';
  showCount?: boolean;
  initialCount?: number;
  className?: string;
}

export function LikeButton({ itemId, initialLiked = false, onToggle, size = 'md', showCount = false, initialCount = 0, className }: LikeButtonProps) {
  const [liked, setLiked] = useState(initialLiked);
  const [count, setCount] = useState(initialCount);
  const iconSize = size === 'sm' ? 'w-4 h-4' : size === 'lg' ? 'w-7 h-7' : 'w-5 h-5';
  const buttonSize = size === 'sm' ? 'p-1.5' : size === 'lg' ? 'p-3' : 'p-2';

  const handleToggle = () => {
    const next = !liked;
    setLiked(next);
    setCount(prev => next ? prev + 1 : Math.max(0, prev - 1));
    toast.success(next ? 'Added to favorites' : 'Removed from favorites');
    onToggle?.(next);
  };

  return (
    <button onClick={handleToggle} className={cn('rounded-full transition-all duration-200 hover:scale-110 active:scale-95', buttonSize, className)} aria-label={liked ? 'Remove from favorites' : 'Add to favorites'}>
      <FiHeart className={cn(iconSize, 'transition-colors duration-200', liked ? 'fill-red-500 text-red-500' : 'text-gray-400 hover:text-red-400')} />
      {showCount && <span className="text-xs text-gray-500 ml-1">{count}</span>}
    </button>
  );
}
