// backend-ts/templates/astro-cloud/src/components/UserMenu.tsx
import { useState, useRef, useEffect } from "react";
import { signOut, useSession } from "../lib/auth-client";

export default function UserMenu() {
  const { data: session } = useSession();
  const [open, setOpen] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node)) {
        setOpen(false);
      }
    };
    document.addEventListener("mousedown", handleClickOutside);
    return () => document.removeEventListener("mousedown", handleClickOutside);
  }, []);

  if (!session?.user) return null;

  const initials = (session.user.name || session.user.email || "U")
    .split(" ")
    .map((w: string) => w[0])
    .join("")
    .toUpperCase()
    .slice(0, 2);

  const handleLogout = async () => {
    await signOut();
    window.location.href = "/login";
  };

  return (
    <div className="relative" ref={menuRef}>
      <button
        onClick={() => setOpen(!open)}
        className="flex items-center gap-2 rounded-full hover:opacity-80 transition"
      >
        {session.user.image ? (
          <img src={session.user.image} alt="" className="w-8 h-8 rounded-full" />
        ) : (
          <div className="w-8 h-8 rounded-full bg-purple-600 text-white flex items-center justify-center text-sm font-medium">
            {initials}
          </div>
        )}
      </button>

      {open && (
        <div className="absolute right-0 mt-2 w-56 bg-white/10 backdrop-blur-xl border border-white/20 rounded-xl shadow-lg py-2 z-50">
          <div className="px-4 py-2 border-b border-white/10">
            <p className="text-sm font-medium text-white truncate">{session.user.name}</p>
            <p className="text-xs text-slate-400 truncate">{session.user.email}</p>
          </div>
          <button
            onClick={handleLogout}
            className="w-full px-4 py-2 text-left text-sm text-red-400 hover:bg-red-500/10 transition"
          >
            Sign out
          </button>
        </div>
      )}
    </div>
  );
}

// backend-ts/templates/vue-cloud/src/components/UserMenu.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'
import { signOut, useSession } from '../lib/auth-client'

const { data: session } = useSession()
const open = ref(false)
const menuRef = ref<HTMLDivElement | null>(null)
const router = useRouter()

const user = computed(() => session.value?.user ?? null)

const initials = computed(() => {
  const u = user.value
  if (!u) return ''
  return (u.name || u.email || 'U')
    .split(' ')
    .map((w: string) => w[0])
    .join('')
    .toUpperCase()
    .slice(0, 2)
})

function handleClickOutside(e: MouseEvent) {
  if (menuRef.value && !menuRef.value.contains(e.target as Node)) {
    open.value = false
  }
}

onMounted(() => document.addEventListener('mousedown', handleClickOutside))
onUnmounted(() => document.removeEventListener('mousedown', handleClickOutside))

async function handleLogout() {
  await signOut()
  router.push('/login')
}
</script>

<template>
  <div v-if="user" class="relative" ref="menuRef">
    <button
      @click="open = !open"
      class="flex items-center gap-2 rounded-full hover:opacity-80 transition"
    >
      <img v-if="user.image" :src="user.image" alt="" class="w-8 h-8 rounded-full" />
      <div
        v-else
        class="w-8 h-8 rounded-full bg-blue-600 text-white flex items-center justify-center text-sm font-medium"
      >
        {{ initials }}
      </div>
    </button>

    <div
      v-if="open"
      class="absolute right-0 mt-2 w-56 bg-white rounded-xl shadow-lg border border-gray-100 py-2 z-50"
    >
      <div class="px-4 py-2 border-b border-gray-100">
        <p class="text-sm font-medium text-gray-900 truncate">{{ user.name }}</p>
        <p class="text-xs text-gray-500 truncate">{{ user.email }}</p>
      </div>
      <button
        @click="handleLogout"
        class="w-full px-4 py-2 text-left text-sm text-red-600 hover:bg-red-50 transition"
      >
        Sign out
      </button>
    </div>
  </div>
</template>
